# Setup
title:               Subhandu Rawat
tagline:             'Blog'
description:         'Welcome to my blog. Here I write about Turbulence, Aerodynamics, Data science and Programming'
production_url:       https://rawatsu.github.io/blog
baseurl:             '/blog'
paginate:            5
#permalink:           pretty
permalink: /:categories/:title/

# About/contact
author:
  name:              Subhandu Rawat
  email:             subhandurawat@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

